### ISSUE TITLE
The format ?

### ISSUE THREAD

**Issue by hmyh1202** [shizhuoxing/Full-Length-RNA-Toolkit#1]
What the format of the input file ?

**Comment by shizhuoxing** [comment]
hi, i just upload a binary version software for polyA tail detection: https://github.com/shizhuoxing/Full-Length-RNA-Toolkit/blob/master/bin/denovo_polyAtail_trim

**Comment by hmyh1202** [comment]
Hi :
my example sequence is as below:
>seq1
actagtcgatACCGTAGCTAGCTGATCGTAGCTGATGCTAGTCGTGATAAACGTCGATGCTGATCGTcagctagtcgtaagctgataaaaagaaaacaaaaaaaaaaa

$cat test.fa.trimmedPolyAtail.fa
>seq1
actagtcgatACCGTAGCTAGCTGATCGTAGCTGATGCTAGTCGTGATAAACGTCGATGCTGATCGTcagctagtcgtaagctgataaaaagaaaacaaaaaaaaaaa
$cat test.fa.polyAstat.xls
SeqID   TrimmedPolyASeqLength   PolyALength     PolyA
seq1    108     0       NA

So can you show your usage of this software and format of inputfile, and the  threshold value to detect the polyA tail. The more detail the better, thanks.

The Best !

**Comment by hmyh1202** [comment]
Some readme or help should show in the github

**Comment by shizhuoxing** [comment]
Hi, All bases need uppercase.

**Comment by shizhuoxing** [comment]
In addition, input file must be FASTA format, in your case:
```
$ cat test.fa
>seq1
ACTAGTCGATACCGTAGCTAGCTGATCGTAGCTGATGCTAGTCGTGATAAACGTCGATGCTGATCGTCAGCTAGTCGTAAGCTGATAAAAAGAAAACAAAAAAAAAAA
```
